name: starter-github-actions
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13, 14]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: poc
      - run: pwd && ls -al
      - uses: actions/setup-node@v3
        with:
          node-version: {{ matrix.node-version }}
      - run: npm install -g bats
      - run: bats -v