name: Deploy via dispatch
on:
  repository_dispatch:
    types: [deploy-to-platform]

  push:
    branches:
      - dispatch


jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info
        shell: bash
        run: |
          echo "client_payload: ${{ github.event.client_payload.tfvars.programme_name }}"
          echo "github_event: ${{ ToJson(github.event.client_payload.tfvars) }}"
          
          echo "plan - event.pr.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "github.sha: ${{ github.sha }}"
          echo "apply: ${{ github.event.commits[1].id }}"
          
          echo "before: ${{ github.event.before }}"
          echo "after: ${{ github.event.after }}"
          
          echo "event number: ${{ github.event.number }}"
          echo "issue number: ${{ github.event.issue.number }}"
          
          echo "pr: ${{ github.event.head_commit.message }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
      - name: Output Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"

  deploy-config:
    env:
      GITHBU_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TFVARS_FILE: "release/ci/config/terraform.tfvars.json"

    name: Terraform plan/apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: release
      - name: tfvars from payload
        run: |
          set -x
          echo "${{ ToJson(github.event.client_payload.tfvars) }}"
          echo "${{ github.event.client_payload.tfvars.programme_name }}"
          echo "${{ ToJson(github.event.client_payload.tfvars) }}" > "$TFVARS_FILE"
          tree release
          cat "$TFVARS_FILE"