name: Deploy via dispatch
on:
  repository_dispatch:
    types: [deploy-to-platform]

  push:
    branches:
      - dispatch


jobs:
  deploy-config:
    env:
      GITHBU_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TFVARS_FILE: "release/ci/config/terraform.tfvars.json"

    name: Terraform plan/apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: release
      - name: tfvars from payload
        run: |
          set -x
          echo "---------------------tfvars-----------------------------"
          echo "${{ ToJson(github.event.client_payload.tfvars) }}"
          echo "---------------------tfvars pipe jq -----------------------------"
          echo "${{ ToJson(github.event.client_payload.tfvars) }}" | jq
          echo "---------------------programme_name-----------------------------"          
          echo "${{ github.event.client_payload.tfvars.programme_name }}"
          echo "${{ ToJson(github.event.client_payload.tfvars) }}" | jq > "$TFVARS_FILE"
          tree release
          cat "$TFVARS_FILE"