name: secrets-workflow
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          tenant_id: ${{ secrets.TENANT_ID }}
        run: |
          echo "$tenant_id"