name: secrets-workflow
on:
  push:
    branches:
      - poc
env:
  AZURE_TENANT_ID: ${{secrets.TENANT_ID}}

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      AZURE_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
      - name: Retrieve secret
        env:
          tenant_id: ${{ secrets.TENANT_ID }}
        run: |
          echo "$tenant_id"
          printenv
      - name: Inspect Secrt
        run: |
          ls -al
          echo 'displaying secret...:'
          cut -c1-10 key
          # echo -n "${{ secrets.TENANT_ID }}" >> key && cut -c1-3 key && cat key | cut -c1-5     
          printenv | grep AZURE
