name: secrets-workflow
on: [push]
  branch:
    - poc
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          tenant_id: ${{ secrets.TENANT_ID }}
        run: |
          echo "$tenant_id"
      - run: 'echo ${{ secrets.TENANT_ID }} | base64 -d > key'
        shell: bash
        env:
          AZURE_TENANT_ID: ${{secrets.TENANT_ID}}
      - name: List Dir
        run: |
          ls -al
          cat key
          printenv | grep AZURE
