name: secrets-workflow
on:
  push:
    branches:
      - poc
env:
  AZURE_TENANT_ID: ${{secrets.TENANT_ID}}

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}

    steps:
      - name: Retrieve secret
        env:
          tenant_id: ${{ secrets.TENANT_ID }}
        run: |
          echo "$tenant_id"
          printenv
      - name: Inspect Secret
        run: |
          echo "${{ secrets.TENANT_ID }}" >> key1
          ls -al       
          echo 'displaying secret...:'   
          secret_length=$(expr length ${{ secrets.TENANT_ID }})
          echo $secret_length
          cut -c1-$secret_length key1
          echo -n "${{ secrets.TENANT_ID }}" >> key && cut -c1-3 key # && cat key | cut -c1-5     
          printenv | grep AZURE
          expr length ${{ secrets.TENANT_ID }}
