name: secrets-workflow
on:
  push:
    branches:
      - poc
env:
  AZURE_TENANT_ID: ${{secrets.TENANT_ID}}

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      AZURE_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
      - name: Retrieve secret
        env:
          tenant_id: ${{ secrets.TENANT_ID }}
        run: |
          echo "$tenant_id"
          printenv
      - run: 'echo ${{ secrets.TENANT_ID }} | base64 -d > key'
        shell: bash
      - name: List Dir
        run: |
          ls -al
          cat key
          printenv | grep AZURE
